//
//  UserDefaultKey.swift
//  FDTX
//
//  Created by fandong on 2017/9/11.
//  Copyright © 2017年 fandong. All rights reserved.
//

import Foundation

let USER_DEFAULT_KEY_ISLOGIN    = "USER_DEFAULT_KEY_ISLOGIN"
let USER_DEFAULT_KEY_UID        = "USER_DEFAULT_KEY_UID"
let USER_DEFAULT_KEY_NICKNAME   = "USER_DEFAULT_KEY_NICKNAME"
let USER_DEFAULT_KEY_INTRODUCE  = "USER_DEFAULT_KEY_INTRODUCE"
let USER_DEFAULT_KEY_ICON       = "USER_DEFAULT_KEY_ICON"

let USER_DEFAULT_KEY_NIGHTMODE = "USER_DEFAULT_KEY_NIGHTMODE"
